"""Pydantic response schemas for BE-012 Part 4's Insight Engine endpoints:
``GET /analytics/insights/business``, ``GET /analytics/insights/operational``.
"""

from __future__ import annotations

from pydantic import BaseModel

__all__ = [
    "InsightItem",
    "BusinessInsightsResponse",
    "OperationalRecommendationsResponse",
]

_RULE_ENGINE_NOTE = (
    "Generated by a real, deterministic RULE ENGINE over real aggregated "
    "platform data (app.domains.analytics.insights) -- NOT by an AI/LLM. "
    "Each insight fires only when a real number crosses a real, configured "
    "threshold (see app.core.config.Settings and docs/analytics/FLOW.md for "
    "the exact rule set). This is 'AI-ready' only in the sense that a real "
    "LLM integration could later enhance or replace this text generation -- "
    "it does not claim to BE one today."
)


class InsightItem(BaseModel):
    rule: str
    severity: str
    message: str


class BusinessInsightsResponse(BaseModel):
    generated_at: str
    insights: list[InsightItem]
    rule_engine_note: str = _RULE_ENGINE_NOTE


class OperationalRecommendationsResponse(BaseModel):
    generated_at: str
    recommendations: list[InsightItem]
    rule_engine_note: str = _RULE_ENGINE_NOTE
