"""Data-driven RBAC seed data and an idempotent seeding entrypoint.

Nothing in this module is a hand-written list of individual permission or
role-permission rows. Instead:

* :data:`MODULE_ACTIONS` maps each :class:`PermissionModule` to the subset of
  :class:`PermissionAction` values that apply to it (e.g. ``Approve`` makes
  sense for ``Voucher``/``Campaigns``/``Router Provisioning`` but not for
  ``Dashboard``). ``permissions`` rows are generated by iterating this
  mapping.
* :data:`MODULE_NARROWEST_SCOPE` maps each module to the narrowest
  :class:`ScopeType` at which it is meaningful (e.g. ``Guest Users`` is
  meaningful down to ``LOCATION``; ``System Settings`` only at ``GLOBAL``).
  ``permission_scopes`` rows are generated from this -- a permission is
  valid at its module's narrowest scope *and every broader scope* (a
  GLOBAL-scoped role can always exercise a location-level permission; the
  reverse is not true). This is what keeps e.g. "Super Admin holds every
  permission" from ever conflicting with a narrower permission_scopes
  constraint: GLOBAL is always in range.
* :data:`SYSTEM_ROLES` describes each of the 15 seeded system roles as a
  *default grant level per module, with per-module overrides*
  (:class:`GrantLevel`: ``NONE`` / ``READ`` / ``OPERATE`` / ``FULL``) rather
  than a literal permission-key list. ``role_permissions`` rows are
  generated by expanding each role's levels against ``MODULE_ACTIONS``.

Run via ``python -m app.domains.rbac.seed`` or by calling
:func:`seed_rbac` with an ``AsyncSession`` (e.g. from an application
startup hook or a one-off script). Safe to run repeatedly: every insert is
guarded by an existence check first.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum

from sqlalchemy.ext.asyncio import AsyncSession

from .enums import SCOPE_HIERARCHY_ORDER, PermissionAction, PermissionModule, ScopeType
from .models import Permission, PermissionGroup
from .repository import RBACRepository

logger = logging.getLogger(__name__)

# ============================================================================
# Module -> applicable actions
# ============================================================================

_A = PermissionAction

MODULE_ACTIONS: Mapping[PermissionModule, tuple[PermissionAction, ...]] = {
    PermissionModule.DASHBOARD: (_A.VIEW,),
    PermissionModule.USERS: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXPORT,
        _A.IMPORT,
        _A.ASSIGN,
        _A.MANAGE,
    ),
    PermissionModule.ROLES: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.ASSIGN,
        _A.MANAGE,
    ),
    PermissionModule.PERMISSIONS: (_A.READ, _A.ASSIGN, _A.MANAGE),
    PermissionModule.ORGANIZATIONS: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.MANAGE,
    ),
    PermissionModule.LOCATIONS: (_A.CREATE, _A.READ, _A.UPDATE, _A.DELETE, _A.MANAGE),
    PermissionModule.ROUTERS: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.MANAGE,
        _A.EXECUTE,
    ),
    PermissionModule.ROUTER_PROVISIONING: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXECUTE,
        _A.APPROVE,
        _A.MANAGE,
    ),
    PermissionModule.TEMPLATES: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXPORT,
        _A.IMPORT,
        _A.MANAGE,
    ),
    PermissionModule.CAPTIVE_PORTAL: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.MANAGE,
    ),
    PermissionModule.GUEST_WIFI: (_A.CREATE, _A.READ, _A.UPDATE, _A.DELETE, _A.MANAGE),
    PermissionModule.GUEST_USERS: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXPORT,
        _A.MANAGE,
    ),
    PermissionModule.GUEST_SESSIONS: (
        _A.READ,
        _A.DELETE,
        _A.EXPORT,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    PermissionModule.GUEST_ACCESS: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.MANAGE,
    ),
    PermissionModule.GUEST_TEAMS: (
        _A.CREATE,
        _A.READ,
        _A.DELETE,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    PermissionModule.OTP: (_A.CREATE, _A.READ, _A.EXECUTE, _A.MANAGE),
    PermissionModule.VOUCHER: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXPORT,
        _A.IMPORT,
        _A.APPROVE,
        _A.MANAGE,
    ),
    PermissionModule.CAMPAIGNS: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.APPROVE,
        _A.EXPORT,
        _A.MANAGE,
    ),
    PermissionModule.RADIUS: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    PermissionModule.WIREGUARD: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    PermissionModule.FIREWALL: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    PermissionModule.DHCP: (_A.CREATE, _A.READ, _A.UPDATE, _A.DELETE, _A.MANAGE),
    PermissionModule.DNS: (_A.CREATE, _A.READ, _A.UPDATE, _A.DELETE, _A.MANAGE),
    PermissionModule.HOTSPOT: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.MANAGE,
        _A.EXECUTE,
    ),
    # Extended for the Queue Management Engine (a vendor-agnostic
    # bandwidth/QoS orchestrator) -- this key was already seeded, ahead of
    # any real domain existing, specifically for this concern, but with a
    # narrower action tuple than a full-CRUD+execute domain needs. CREATE/
    # DELETE (QueueProfile CRUD) and EXECUTE (apply/remove/reset a queue
    # on a real device, mirroring ROUTER_PROVISIONING's/
    # PROVISIONING_ENGINE's own identical "device-affecting action" use of
    # EXECUTE) are additive here -- no existing role's own grants change
    # shape, only what this module's own actions expand into.
    PermissionModule.BANDWIDTH: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    PermissionModule.ANALYTICS: (_A.READ, _A.EXPORT, _A.VIEW),
    PermissionModule.REPORTS: (_A.READ, _A.EXPORT, _A.VIEW, _A.MANAGE),
    PermissionModule.MONITORING: (_A.READ, _A.VIEW, _A.MANAGE),
    PermissionModule.ALERTS: (_A.READ, _A.UPDATE, _A.DELETE, _A.VIEW, _A.MANAGE),
    PermissionModule.NOTIFICATIONS: (_A.READ, _A.UPDATE, _A.DELETE, _A.MANAGE),
    PermissionModule.BILLING: (_A.READ, _A.UPDATE, _A.EXPORT, _A.MANAGE),
    PermissionModule.INVOICES: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXPORT,
        _A.APPROVE,
        _A.MANAGE,
    ),
    PermissionModule.SUBSCRIPTIONS: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.MANAGE,
    ),
    PermissionModule.WHITE_LABEL: (_A.READ, _A.UPDATE, _A.MANAGE),
    PermissionModule.API_KEYS: (_A.CREATE, _A.READ, _A.DELETE, _A.MANAGE),
    PermissionModule.AUDIT_LOGS: (_A.READ, _A.EXPORT, _A.VIEW),
    PermissionModule.SYSTEM_SETTINGS: (_A.READ, _A.UPDATE, _A.MANAGE),
    PermissionModule.AI_ASSISTANT: (_A.READ, _A.EXECUTE, _A.VIEW, _A.MANAGE),
    PermissionModule.POLICY: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    # Mirrors OTP's identical action shape: jobs are created and driven
    # through their lifecycle (start/retry/rollback/cancel, all EXECUTE),
    # never directly updated/deleted by a user -- there is no
    # UPDATE/DELETE/APPROVE action for a ProvisionJob.
    PermissionModule.PROVISIONING_ENGINE: (_A.CREATE, _A.READ, _A.EXECUTE, _A.MANAGE),
    # ISP Management: full CRUD on isp_links plus EXECUTE for the manual
    # health-check/failover/failback triggers -- mirrors
    # PermissionModule.BANDWIDTH's own identical CRUD+EXECUTE+MANAGE shape
    # for the same "reusable inventory row + a real device-facing action"
    # profile.
    PermissionModule.ISP: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    # ISP Routing: a pure rules/inventory domain with no live device push
    # in this pass (see app.domains.isp_routing.service's own module
    # docstring) -- no EXECUTE action, unlike PermissionModule.ISP's own
    # manual health-check/failover/failback triggers.
    PermissionModule.ISP_ROUTING: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.MANAGE,
    ),
    # VLAN Management: same CRUD+MANAGE shape as PermissionModule
    # .ISP_ROUTING -- a pure rules/inventory domain, no EXECUTE action in
    # this pass (see app.domains.vlan.service's own module docstring).
    PermissionModule.VLAN: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.MANAGE,
    ),
    # PermissionModule.DHCP's own action tuple already exists above
    # (seeded ahead of any real domain, like PermissionModule.BANDWIDTH
    # was for queue_management) -- this build reuses it as-is for
    # app.domains.dhcp rather than minting a second key, and its shape
    # already matches (CREATE/READ/UPDATE/DELETE/MANAGE, no EXECUTE).
    # MAC Authorization: CRUD plus IMPORT/EXPORT for its own bulk
    # operations -- mirrors PermissionModule.VOUCHER's own inclusion of
    # both actions for the identical "bulk-load/download a whitelist"
    # shape.
    PermissionModule.MAC_AUTHORIZATION: (
        _A.CREATE,
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.IMPORT,
        _A.EXPORT,
        _A.MANAGE,
    ),
    # Connected Device Management: no CREATE -- rows only ever come into
    # existence via a real device sync (see
    # app.domains.connected_devices.service's own module docstring), so
    # there is no user-facing "create a connected device" action. EXECUTE
    # covers disconnect/refresh/sync/block/unblock/whitelist.
    PermissionModule.CONNECTED_DEVICES: (
        _A.READ,
        _A.UPDATE,
        _A.DELETE,
        _A.EXECUTE,
        _A.MANAGE,
    ),
    # Device Synchronization: read-only history plus EXECUTE (trigger a
    # sync) -- no CREATE/UPDATE/DELETE, since DeviceSyncRun rows are
    # immutable and only ever created by the sync action itself (see
    # app.domains.device_sync.models's own module docstring).
    PermissionModule.DEVICE_SYNC: (_A.READ, _A.EXECUTE, _A.MANAGE),
    # Network Configuration Management: read (preview/list/get/diff
    # versions) plus EXECUTE (push/rollback -- the actions that actually
    # queue a real device push) -- no CREATE/UPDATE/DELETE, since this
    # domain owns no table of its own; every version it creates lives in
    # app.domains.router_provisioning's own ConfigVersion, mirroring
    # DEVICE_SYNC's identical "no CRUD resource of its own" shape.
    PermissionModule.NETWORK_CONFIG: (_A.READ, _A.EXECUTE, _A.MANAGE),
    # QoS & VOIP Priority: a plain CRUD rules/inventory domain -- no
    # EXECUTE, since this domain has no device-facing action of its own
    # (real device push is composed via app.domains.network_config's own
    # EXECUTE-gated push endpoint instead), mirroring DHCP/VLAN's
    # identical shape.
    PermissionModule.QOS: (_A.CREATE, _A.READ, _A.UPDATE, _A.DELETE, _A.MANAGE),
}

MODULE_DISPLAY_NAMES: Mapping[PermissionModule, str] = {
    PermissionModule.DASHBOARD: "Dashboard",
    PermissionModule.USERS: "Users",
    PermissionModule.ROLES: "Roles",
    PermissionModule.PERMISSIONS: "Permissions",
    PermissionModule.ORGANIZATIONS: "Organizations",
    PermissionModule.LOCATIONS: "Locations",
    PermissionModule.ROUTERS: "Routers",
    PermissionModule.ROUTER_PROVISIONING: "Router Provisioning",
    PermissionModule.TEMPLATES: "Templates",
    PermissionModule.CAPTIVE_PORTAL: "Captive Portal",
    PermissionModule.GUEST_WIFI: "Guest WiFi",
    PermissionModule.GUEST_USERS: "Guest Users",
    PermissionModule.GUEST_SESSIONS: "Guest Sessions",
    PermissionModule.GUEST_ACCESS: "Guest Access Control",
    PermissionModule.GUEST_TEAMS: "Guest Teams",
    PermissionModule.OTP: "OTP",
    PermissionModule.VOUCHER: "Voucher",
    PermissionModule.CAMPAIGNS: "Campaigns",
    PermissionModule.RADIUS: "Radius",
    PermissionModule.WIREGUARD: "WireGuard",
    PermissionModule.FIREWALL: "Firewall",
    PermissionModule.DHCP: "DHCP Pool Management",
    PermissionModule.DNS: "DNS",
    PermissionModule.HOTSPOT: "Hotspot Settings",
    PermissionModule.BANDWIDTH: "Bandwidth",
    PermissionModule.ANALYTICS: "Analytics",
    PermissionModule.REPORTS: "Reports",
    PermissionModule.MONITORING: "Monitoring",
    PermissionModule.ALERTS: "Alerts",
    PermissionModule.NOTIFICATIONS: "Notifications",
    PermissionModule.BILLING: "Billing",
    PermissionModule.INVOICES: "Invoices",
    PermissionModule.SUBSCRIPTIONS: "Subscriptions",
    PermissionModule.WHITE_LABEL: "White Label",
    PermissionModule.API_KEYS: "API Keys",
    PermissionModule.AUDIT_LOGS: "Audit Logs",
    PermissionModule.SYSTEM_SETTINGS: "System Settings",
    PermissionModule.AI_ASSISTANT: "AI Assistant",
    PermissionModule.POLICY: "Policy",
    PermissionModule.PROVISIONING_ENGINE: "Provisioning Engine",
    PermissionModule.ISP: "ISP Management",
    PermissionModule.ISP_ROUTING: "ISP Routing",
    PermissionModule.VLAN: "VLAN Management",
    PermissionModule.MAC_AUTHORIZATION: "MAC Authorization",
    PermissionModule.CONNECTED_DEVICES: "Connected Devices",
    PermissionModule.DEVICE_SYNC: "Device Synchronization",
    PermissionModule.NETWORK_CONFIG: "Network Configuration Management",
    PermissionModule.QOS: "QoS & VOIP Priority",
}

# The narrowest scope each module's permissions are meaningful at. A
# permission is seeded as valid at this scope *and every broader scope*
# (see module docstring).
MODULE_NARROWEST_SCOPE: Mapping[PermissionModule, ScopeType] = {
    PermissionModule.DASHBOARD: ScopeType.LOCATION,
    PermissionModule.USERS: ScopeType.ORGANIZATION,
    PermissionModule.ROLES: ScopeType.ORGANIZATION,
    PermissionModule.PERMISSIONS: ScopeType.ORGANIZATION,
    PermissionModule.ORGANIZATIONS: ScopeType.ORGANIZATION,
    PermissionModule.LOCATIONS: ScopeType.LOCATION,
    PermissionModule.ROUTERS: ScopeType.ROUTER,
    PermissionModule.ROUTER_PROVISIONING: ScopeType.ROUTER,
    PermissionModule.TEMPLATES: ScopeType.LOCATION,
    PermissionModule.CAPTIVE_PORTAL: ScopeType.LOCATION,
    PermissionModule.GUEST_WIFI: ScopeType.LOCATION,
    PermissionModule.GUEST_USERS: ScopeType.LOCATION,
    PermissionModule.GUEST_SESSIONS: ScopeType.LOCATION,
    PermissionModule.GUEST_ACCESS: ScopeType.LOCATION,
    PermissionModule.GUEST_TEAMS: ScopeType.LOCATION,
    PermissionModule.OTP: ScopeType.LOCATION,
    PermissionModule.VOUCHER: ScopeType.LOCATION,
    PermissionModule.CAMPAIGNS: ScopeType.LOCATION,
    PermissionModule.RADIUS: ScopeType.ROUTER,
    PermissionModule.WIREGUARD: ScopeType.ROUTER,
    PermissionModule.FIREWALL: ScopeType.ROUTER,
    PermissionModule.DHCP: ScopeType.ROUTER,
    PermissionModule.DNS: ScopeType.ROUTER,
    PermissionModule.HOTSPOT: ScopeType.ROUTER,
    PermissionModule.BANDWIDTH: ScopeType.ROUTER,
    PermissionModule.ANALYTICS: ScopeType.LOCATION,
    PermissionModule.REPORTS: ScopeType.LOCATION,
    PermissionModule.MONITORING: ScopeType.ROUTER,
    PermissionModule.ALERTS: ScopeType.LOCATION,
    PermissionModule.NOTIFICATIONS: ScopeType.LOCATION,
    PermissionModule.BILLING: ScopeType.ORGANIZATION,
    PermissionModule.INVOICES: ScopeType.ORGANIZATION,
    PermissionModule.SUBSCRIPTIONS: ScopeType.ORGANIZATION,
    PermissionModule.WHITE_LABEL: ScopeType.ORGANIZATION,
    PermissionModule.API_KEYS: ScopeType.ORGANIZATION,
    PermissionModule.AUDIT_LOGS: ScopeType.ORGANIZATION,
    PermissionModule.SYSTEM_SETTINGS: ScopeType.GLOBAL,
    PermissionModule.AI_ASSISTANT: ScopeType.ORGANIZATION,
    PermissionModule.POLICY: ScopeType.LOCATION,
    # Device-level orchestration, the same narrowest-scope profile
    # ROUTER_PROVISIONING/RADIUS/WIREGUARD/FIREWALL/DHCP/DNS/HOTSPOT/
    # MONITORING already share.
    PermissionModule.PROVISIONING_ENGINE: ScopeType.ROUTER,
    # An ISP link is physically terminated at one router -- same reasoning
    # as PermissionModule.BANDWIDTH's own ScopeType.ROUTER entry above.
    PermissionModule.ISP: ScopeType.ROUTER,
    # A routing rule is scoped to one router's own uplinks -- same
    # reasoning as PermissionModule.ISP's own ScopeType.ROUTER entry above.
    PermissionModule.ISP_ROUTING: ScopeType.ROUTER,
    # A VLAN is a router's own interface-level construct -- same
    # ScopeType.ROUTER reasoning as PermissionModule.ISP/ISP_ROUTING above.
    PermissionModule.VLAN: ScopeType.ROUTER,
    # PermissionModule.DHCP's own ScopeType.ROUTER entry already exists
    # above (seeded ahead of any real domain) and already matches this
    # domain's own scoping (a DHCP pool is scoped to one router's own
    # interfaces) -- reused as-is, no change needed.
    # MAC Authorization has no router concept at all (organization/
    # location scoped only) -- ScopeType.LOCATION mirrors
    # PermissionModule.GUEST_ACCESS's own identical scope for the
    # closest analogous domain (also a MAC-address-keyed, org/location-
    # scoped concept).
    PermissionModule.MAC_AUTHORIZATION: ScopeType.LOCATION,
    # A connected device is scoped to one router's own network -- same
    # ScopeType.ROUTER reasoning as PermissionModule.ISP/VLAN/DHCP above.
    PermissionModule.CONNECTED_DEVICES: ScopeType.ROUTER,
    # A device sync run is scoped to one router -- same ScopeType.ROUTER
    # reasoning as PermissionModule.CONNECTED_DEVICES above.
    PermissionModule.DEVICE_SYNC: ScopeType.ROUTER,
    # A pushed/rolled-back network config targets one router at a time --
    # identical ScopeType.ROUTER reasoning.
    PermissionModule.NETWORK_CONFIG: ScopeType.ROUTER,
    # A QoS traffic rule is scoped to one router -- identical ScopeType
    # .ROUTER reasoning as PermissionModule.DHCP/VLAN above.
    PermissionModule.QOS: ScopeType.ROUTER,
}


def permission_key(module: PermissionModule, action: PermissionAction) -> str:
    return f"{module.value}.{action.value}"


def allowed_scope_types_for_module(module: PermissionModule) -> tuple[ScopeType, ...]:
    """Every scope from ``GLOBAL`` down to the module's narrowest scope, inclusive."""
    narrowest_order = SCOPE_HIERARCHY_ORDER[MODULE_NARROWEST_SCOPE[module]]
    return tuple(
        scope for scope in ScopeType if SCOPE_HIERARCHY_ORDER[scope] <= narrowest_order
    )


# ============================================================================
# System roles: default grant level per module, with overrides
# ============================================================================


class GrantLevel(StrEnum):
    """How much of a module's applicable actions a role gets by default."""

    NONE = "none"
    READ = "read"
    OPERATE = "operate"
    FULL = "full"


def expand_grant_level(
    level: GrantLevel, actions: tuple[PermissionAction, ...]
) -> tuple[PermissionAction, ...]:
    if level == GrantLevel.NONE:
        return ()
    if level == GrantLevel.READ:
        return tuple(
            a for a in actions if a in (PermissionAction.READ, PermissionAction.VIEW)
        )
    if level == GrantLevel.OPERATE:
        return tuple(
            a
            for a in actions
            if a not in (PermissionAction.MANAGE, PermissionAction.DELETE)
        )
    return actions  # FULL


@dataclass(frozen=True)
class SystemRoleDefinition:
    name: str
    slug: str
    description: str
    scope_type: ScopeType
    default_level: GrantLevel
    overrides: Mapping[PermissionModule, GrantLevel] = field(default_factory=dict)

    def grants(self) -> dict[PermissionModule, tuple[PermissionAction, ...]]:
        resolved: dict[PermissionModule, tuple[PermissionAction, ...]] = {}
        for module, actions in MODULE_ACTIONS.items():
            level = self.overrides.get(module, self.default_level)
            expanded = expand_grant_level(level, actions)
            if expanded:
                resolved[module] = expanded
        return resolved


_M = PermissionModule
_L = GrantLevel

# Scope-type design decisions (see RBAC_ARCHITECTURE.md for the full write-up):
# - Super Admin / Platform Admin / Platform Support / Billing Manager: GLOBAL
#   (platform-wide operations spanning every tenant).
# - MSP Owner / MSP Admin: ORGANIZATION. The ScopeType enum has no dedicated
#   MSP level (MSP has no domain yet); an MSP is modeled, once the
#   Organization domain exists, as an Organization row flagged as an MSP
#   container, so ORGANIZATION is the closest existing fit today.
# - Organization Owner / Organization Admin: ORGANIZATION.
# - Network Administrator / Location Manager / Reception Staff / Helpdesk /
#   Guest Operator: LOCATION (day-to-day, site-level roles).
# - Read Only / Auditor: ORGANIZATION (the common "tenant-wide visibility"
#   need; can be cloned to GLOBAL for a platform-wide auditor if needed).
SYSTEM_ROLES: tuple[SystemRoleDefinition, ...] = (
    SystemRoleDefinition(
        name="Super Admin",
        slug="super-admin",
        description="Unrestricted platform-wide access to every module and action.",
        scope_type=ScopeType.GLOBAL,
        default_level=_L.FULL,
    ),
    SystemRoleDefinition(
        name="Platform Admin",
        slug="platform-admin",
        description=(
            "Platform-wide administrative access, short of core system settings."
        ),
        scope_type=ScopeType.GLOBAL,
        default_level=_L.FULL,
        overrides={_M.SYSTEM_SETTINGS: _L.OPERATE, _M.WHITE_LABEL: _L.OPERATE},
    ),
    SystemRoleDefinition(
        name="Platform Support",
        slug="platform-support",
        description=(
            "Read-heavy platform support access with limited operational actions."
        ),
        scope_type=ScopeType.GLOBAL,
        default_level=_L.READ,
        overrides={
            _M.USERS: _L.OPERATE,
            _M.GUEST_USERS: _L.OPERATE,
            _M.GUEST_SESSIONS: _L.OPERATE,
            _M.GUEST_ACCESS: _L.OPERATE,
            _M.MAC_AUTHORIZATION: _L.OPERATE,
            _M.GUEST_TEAMS: _L.OPERATE,
            _M.ALERTS: _L.OPERATE,
            _M.NOTIFICATIONS: _L.OPERATE,
            _M.MONITORING: _L.OPERATE,
        },
    ),
    SystemRoleDefinition(
        name="Billing Manager",
        slug="billing-manager",
        description="Manages platform-wide billing, invoices, and subscriptions.",
        scope_type=ScopeType.GLOBAL,
        default_level=_L.NONE,
        overrides={
            _M.BILLING: _L.FULL,
            _M.INVOICES: _L.FULL,
            _M.SUBSCRIPTIONS: _L.FULL,
            _M.DASHBOARD: _L.READ,
            _M.REPORTS: _L.READ,
            _M.ORGANIZATIONS: _L.READ,
        },
    ),
    SystemRoleDefinition(
        name="MSP Owner",
        slug="msp-owner",
        description=(
            "Full control over an MSP's portfolio of organizations, locations, "
            "and routers (see scope_type note above)."
        ),
        scope_type=ScopeType.ORGANIZATION,
        default_level=_L.OPERATE,
        overrides={
            _M.ORGANIZATIONS: _L.FULL,
            _M.LOCATIONS: _L.FULL,
            _M.ROUTERS: _L.FULL,
            _M.USERS: _L.FULL,
            _M.ROLES: _L.FULL,
            _M.BILLING: _L.OPERATE,
            _M.SYSTEM_SETTINGS: _L.NONE,
            _M.API_KEYS: _L.NONE,
        },
    ),
    SystemRoleDefinition(
        name="MSP Admin",
        slug="msp-admin",
        description=(
            "Day-to-day administration of an MSP's organizations "
            "(see scope_type note)."
        ),
        scope_type=ScopeType.ORGANIZATION,
        default_level=_L.OPERATE,
        overrides={
            _M.ROLES: _L.OPERATE,
            _M.BILLING: _L.READ,
            _M.SYSTEM_SETTINGS: _L.NONE,
            _M.API_KEYS: _L.NONE,
        },
    ),
    SystemRoleDefinition(
        name="Organization Owner",
        slug="organization-owner",
        description=(
            "Full control over a single organization's configuration and operations."
        ),
        scope_type=ScopeType.ORGANIZATION,
        default_level=_L.FULL,
        overrides={
            _M.ORGANIZATIONS: _L.READ,
            _M.PERMISSIONS: _L.READ,
            _M.ROLES: _L.OPERATE,
            _M.SYSTEM_SETTINGS: _L.NONE,
            _M.SUBSCRIPTIONS: _L.READ,
            _M.BILLING: _L.OPERATE,
            _M.INVOICES: _L.OPERATE,
            _M.WHITE_LABEL: _L.OPERATE,
            _M.API_KEYS: _L.OPERATE,
        },
    ),
    SystemRoleDefinition(
        name="Organization Admin",
        slug="organization-admin",
        description="Day-to-day administration of a single organization.",
        scope_type=ScopeType.ORGANIZATION,
        default_level=_L.OPERATE,
        overrides={
            _M.ORGANIZATIONS: _L.READ,
            _M.PERMISSIONS: _L.READ,
            _M.ROLES: _L.READ,
            _M.SYSTEM_SETTINGS: _L.NONE,
            _M.SUBSCRIPTIONS: _L.READ,
            _M.BILLING: _L.READ,
            _M.INVOICES: _L.READ,
            _M.API_KEYS: _L.NONE,
            _M.WHITE_LABEL: _L.READ,
        },
    ),
    SystemRoleDefinition(
        name="Network Administrator",
        slug="network-administrator",
        description="Full technical control over networking at a single location.",
        scope_type=ScopeType.LOCATION,
        default_level=_L.NONE,
        overrides={
            _M.ROUTERS: _L.FULL,
            _M.ROUTER_PROVISIONING: _L.FULL,
            _M.PROVISIONING_ENGINE: _L.FULL,
            _M.RADIUS: _L.FULL,
            _M.WIREGUARD: _L.FULL,
            _M.FIREWALL: _L.FULL,
            _M.DHCP: _L.FULL,
            _M.DNS: _L.FULL,
            _M.HOTSPOT: _L.FULL,
            _M.BANDWIDTH: _L.FULL,
            _M.ISP: _L.FULL,
            _M.ISP_ROUTING: _L.FULL,
            _M.VLAN: _L.FULL,
            _M.CONNECTED_DEVICES: _L.FULL,
            _M.DEVICE_SYNC: _L.FULL,
            _M.NETWORK_CONFIG: _L.FULL,
            _M.QOS: _L.FULL,
            _M.POLICY: _L.OPERATE,
            _M.MONITORING: _L.FULL,
            _M.ALERTS: _L.OPERATE,
            _M.DASHBOARD: _L.READ,
            _M.ANALYTICS: _L.READ,
            _M.REPORTS: _L.READ,
            _M.TEMPLATES: _L.OPERATE,
            _M.CAPTIVE_PORTAL: _L.OPERATE,
            _M.LOCATIONS: _L.READ,
        },
    ),
    SystemRoleDefinition(
        name="Location Manager",
        slug="location-manager",
        description="Manages guest-facing operations and staff at a single location.",
        scope_type=ScopeType.LOCATION,
        default_level=_L.NONE,
        overrides={
            _M.LOCATIONS: _L.OPERATE,
            _M.GUEST_WIFI: _L.OPERATE,
            _M.GUEST_USERS: _L.OPERATE,
            _M.GUEST_SESSIONS: _L.OPERATE,
            _M.GUEST_ACCESS: _L.OPERATE,
            _M.MAC_AUTHORIZATION: _L.OPERATE,
            _M.GUEST_TEAMS: _L.OPERATE,
            _M.CAPTIVE_PORTAL: _L.OPERATE,
            _M.VOUCHER: _L.OPERATE,
            _M.CAMPAIGNS: _L.OPERATE,
            _M.OTP: _L.OPERATE,
            _M.POLICY: _L.OPERATE,
            _M.DASHBOARD: _L.READ,
            _M.ANALYTICS: _L.READ,
            _M.REPORTS: _L.READ,
            _M.MONITORING: _L.READ,
            _M.ALERTS: _L.READ,
            _M.NOTIFICATIONS: _L.OPERATE,
            _M.HOTSPOT: _L.READ,
        },
    ),
    SystemRoleDefinition(
        name="Reception Staff",
        slug="reception-staff",
        description="Front-desk guest onboarding at a single location.",
        scope_type=ScopeType.LOCATION,
        default_level=_L.NONE,
        overrides={
            _M.GUEST_USERS: _L.OPERATE,
            _M.GUEST_SESSIONS: _L.OPERATE,
            _M.GUEST_ACCESS: _L.OPERATE,
            _M.MAC_AUTHORIZATION: _L.OPERATE,
            _M.GUEST_TEAMS: _L.OPERATE,
            _M.VOUCHER: _L.OPERATE,
            _M.OTP: _L.OPERATE,
            _M.DASHBOARD: _L.READ,
        },
    ),
    SystemRoleDefinition(
        name="Helpdesk",
        slug="helpdesk",
        description="First-line guest support at a single location.",
        scope_type=ScopeType.LOCATION,
        default_level=_L.NONE,
        overrides={
            _M.GUEST_USERS: _L.READ,
            _M.GUEST_SESSIONS: _L.OPERATE,
            _M.GUEST_ACCESS: _L.READ,
            _M.MAC_AUTHORIZATION: _L.READ,
            _M.GUEST_TEAMS: _L.READ,
            _M.POLICY: _L.READ,
            _M.ALERTS: _L.READ,
            _M.NOTIFICATIONS: _L.READ,
            _M.MONITORING: _L.READ,
            _M.DASHBOARD: _L.READ,
            _M.VOUCHER: _L.READ,
        },
    ),
    SystemRoleDefinition(
        name="Read Only",
        slug="read-only",
        description="Read-only visibility across an organization's modules.",
        scope_type=ScopeType.ORGANIZATION,
        default_level=_L.READ,
        # SYSTEM_SETTINGS is GLOBAL-only (see MODULE_NARROWEST_SCOPE) -- an
        # ORGANIZATION-scoped role can never hold any of its permissions.
        overrides={_M.SYSTEM_SETTINGS: _L.NONE},
    ),
    SystemRoleDefinition(
        name="Auditor",
        slug="auditor",
        description=(
            "Read-only visibility plus full access to audit logs, for compliance "
            "review."
        ),
        scope_type=ScopeType.ORGANIZATION,
        default_level=_L.READ,
        overrides={_M.AUDIT_LOGS: _L.FULL, _M.SYSTEM_SETTINGS: _L.NONE},
    ),
    SystemRoleDefinition(
        name="Guest Operator",
        slug="guest-operator",
        description="Narrow, guest-facing operational access at a single location.",
        scope_type=ScopeType.LOCATION,
        default_level=_L.NONE,
        overrides={
            _M.GUEST_WIFI: _L.OPERATE,
            _M.GUEST_USERS: _L.OPERATE,
            _M.GUEST_SESSIONS: _L.OPERATE,
            _M.GUEST_ACCESS: _L.OPERATE,
            _M.MAC_AUTHORIZATION: _L.OPERATE,
            _M.GUEST_TEAMS: _L.OPERATE,
            _M.OTP: _L.OPERATE,
            _M.VOUCHER: _L.OPERATE,
            _M.DASHBOARD: _L.READ,
        },
    ),
)


# ============================================================================
# Seeding entrypoint
# ============================================================================


@dataclass
class SeedSummary:
    permission_groups_created: int = 0
    permissions_created: int = 0
    permission_scopes_created: int = 0
    roles_created: int = 0
    role_permissions_created: int = 0


async def seed_rbac(session: AsyncSession) -> SeedSummary:
    """Idempotently seed permission groups, permissions, permission scopes,
    and the system roles (with their permissions). Safe to call repeatedly:
    every insert is preceded by an existence check."""
    repository = RBACRepository(session)
    summary = SeedSummary()

    group_by_module: dict[PermissionModule, PermissionGroup] = {}
    for module in PermissionModule:
        group = await repository.get_permission_group_by_key(module.value)
        if group is None:
            group = await repository.create_permission_group(
                key=module.value,
                name=MODULE_DISPLAY_NAMES[module],
                sort_order=list(PermissionModule).index(module),
            )
            summary.permission_groups_created += 1
        group_by_module[module] = group

    permission_by_key: dict[str, Permission] = {}
    for module, actions in MODULE_ACTIONS.items():
        group = group_by_module[module]
        for action in actions:
            key = permission_key(module, action)
            permission = await repository.get_permission_by_key(key)
            if permission is None:
                permission = await repository.create_permission(
                    permission_group_id=group.id,
                    key=key,
                    action=action.value,
                    name=f"{MODULE_DISPLAY_NAMES[module]}: {action.value.title()}",
                    description=(
                        f"{action.value.title()} access for the "
                        f"{MODULE_DISPLAY_NAMES[module]} module."
                    ),
                )
                summary.permissions_created += 1

            existing_scopes = set(
                await repository.get_permission_scope_types(permission.id)
            )
            for scope_type in allowed_scope_types_for_module(module):
                if scope_type.value not in existing_scopes:
                    await repository.add_permission_scope(permission.id, scope_type)
                    summary.permission_scopes_created += 1

            permission_by_key[key] = permission

    for role_def in SYSTEM_ROLES:
        role = await repository.get_role_by_slug(role_def.slug, None)
        if role is None:
            role = await repository.create_role(
                name=role_def.name,
                slug=role_def.slug,
                description=role_def.description,
                is_system_role=True,
                is_template=False,
                is_active=True,
                scope_type=role_def.scope_type.value,
                organization_id=None,
                parent_role_id=None,
            )
            summary.roles_created += 1

        existing_permission_ids = {
            row.permission_id for row in await repository.get_role_permissions(role.id)
        }
        for module, actions in role_def.grants().items():
            for action in actions:
                permission = permission_by_key[permission_key(module, action)]
                if permission.id not in existing_permission_ids:
                    await repository.add_role_permission(
                        role.id, permission.id, granted_by=None
                    )
                    summary.role_permissions_created += 1

    logger.info("rbac_seed_completed", extra=vars(summary))
    return summary


def generate_permission_matrix_markdown() -> str:
    """Render ``docs/rbac/PERMISSION_MATRIX.md`` content directly from
    :data:`SYSTEM_ROLES` / :data:`MODULE_ACTIONS`, so the doc can never drift
    from the actual seed data -- regenerate it by re-running this function
    (see ``docs/rbac/PERMISSION_MATRIX.md``'s header for the exact command)."""
    lines: list[str] = [
        "# RBAC Permission Matrix",
        "",
        "Generated directly from `app/domains/rbac/seed.py` "
        "(`SYSTEM_ROLES` x `MODULE_ACTIONS`) -- do not hand-edit the table "
        "below. Regenerate with:",
        "",
        "```bash",
        "cd backend",
        'python -c "from app.domains.rbac.seed import '
        'generate_permission_matrix_markdown as g; print(g())" '
        "> docs/rbac/PERMISSION_MATRIX.md",
        "```",
        "",
        "Cell values are the *default grant level* for that role x module "
        "pair: `-` (none), `R` (read-only), `O` (operate: applicable actions "
        "minus Manage/Delete), or `F` (full: every applicable action for "
        "that module). See `RBAC_ARCHITECTURE.md` for what each level "
        "expands to.",
        "",
    ]

    header = ["Role", "Scope"] + [MODULE_DISPLAY_NAMES[m] for m in PermissionModule]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] * len(header)) + "|")

    level_symbol = {
        GrantLevel.NONE: "-",
        GrantLevel.READ: "R",
        GrantLevel.OPERATE: "O",
        GrantLevel.FULL: "F",
    }
    for role_def in SYSTEM_ROLES:
        row = [role_def.name, role_def.scope_type.value]
        for module in PermissionModule:
            level = role_def.overrides.get(module, role_def.default_level)
            row.append(level_symbol[level])
        lines.append("| " + " | ".join(row) + " |")

    lines.append("")
    lines.append("## Module -> Applicable Actions")
    lines.append("")
    lines.append("| Module | Applicable actions |")
    lines.append("|---|---|")
    for module, actions in MODULE_ACTIONS.items():
        lines.append(
            f"| {MODULE_DISPLAY_NAMES[module]} | "
            f"{', '.join(action.value for action in actions)} |"
        )
    lines.append("")

    return "\n".join(lines)


async def _main() -> None:
    """``python -m app.domains.rbac.seed`` entrypoint."""
    from app.database.session import SessionLocal

    async with SessionLocal() as session:
        summary = await seed_rbac(session)
        await session.commit()
        logger.info("rbac_seed_summary", extra=vars(summary))
        print(summary)  # noqa: T201 -- CLI entrypoint output


if __name__ == "__main__":
    import asyncio

    asyncio.run(_main())
