"""SQLAlchemy ORM models for the Voucher domain.

Both tables extend ``app.database.base.BaseModel`` (UUID PK, timestamps,
soft-delete, audit, version columns) for the same reason every other domain
does -- Alembic autogenerate, ``GenericRepository``, and cross-domain FKs all
keep working uniformly.

## Why ``Voucher.code`` is stored in plaintext, not hashed

Every other short-lived, randomly-generated secret in this codebase is
hashed at rest: ``app.domains.otp.models.OtpRequest.code_hash``,
``app.domains.router.models.RouterProvisioningToken.token_hash``,
``app.domains.router_agent.models.RouterAgentCredential.credential_hash``.
A voucher code is a fundamentally different kind of secret and does **not**
follow that precedent, deliberately:

* An OTP code / provisioning token / agent credential is generated by the
  platform and delivered electronically (SMS, email, a device-side
  handshake) directly to the party who will present it back -- nothing else
  ever needs to *read* it again once issued, so hashing it costs nothing and
  buys real protection if the database is ever read by an unintended party.
* A voucher code is, by this module's whole purpose, a physical or
  verbally-communicated artifact: printed on a card handed to a hotel guest,
  written on a receipt, read aloud at a front desk. The platform must be
  able to display and export it in plaintext after generation (``GET
  .../export``, ``GET .../vouchers``) -- there is no way to "export a hash"
  and have it be useful to a print vendor or a receptionist reading codes
  off a screen. Hashing would defeat this module's core function.
* The threat model is also different in a way that matters here: an OTP
  code's entire value is that it proves the *current* holder of a phone/
  email received it moments ago; a stolen OTP hash is useless without also
  compromising the delivery channel's timing window. A voucher code's value
  is "does this string exist and is it still valid" -- identical whether
  read from a plaintext column or reconstructed from a hash comparison, so
  hashing buys no additional protection against the actual risk (a guest
  finding/guessing a valid code), which is instead mitigated by this
  module's own generation entropy (``constants.VOUCHER_CODE_ALPHABET`` +
  ``VoucherBatch.code_length``) and redemption rate limiting
  (``service.VoucherRedemptionRateLimiter``), not secrecy of the stored row.

This is a documented judgment call, not an oversight: unique-indexed
(``code``, enforced by a real ``UNIQUE`` constraint) so a collision is
caught at the database layer regardless of the in-application collision
retry in ``service._generate_codes``, and every lookup goes through
SQLAlchemy's parameterized queries (``GenericRepository``/plain ``select``)
-- injection safety was never the reason other domains hash their secrets,
and plaintext storage here does not weaken it.

## Why ``Voucher.expires_at`` starts ``NULL`` and is set at first
## redemption, not at generation time

``VoucherBatch.validity_minutes`` documents "how long a voucher grants
access **once redeemed**" -- it is a duration relative to first use, not a
wall-clock deadline fixed at generation. A voucher sitting unredeemed in a
drawer for three weeks has not "used up" any of its post-redemption
validity window; only ``VoucherBatch.batch_expires_at`` (the batch's own,
separate, generation-time shelf-life) can invalidate an unredeemed code.
Computing ``expires_at = generated_at + validity_minutes`` at generation
time would silently expire vouchers nobody had a chance to use yet, which is
backwards from this module's own stated semantics. ``expires_at`` is
therefore ``NULL`` until ``VoucherService.redeem_voucher``'s first
successful call sets it to ``redeemed_at + batch.validity_minutes`` -- see
``service.py``'s module docstring for the full redemption state machine.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import BaseModel

from .constants import VoucherBatchStatus, VoucherStatus


class VoucherBatch(BaseModel):
    """A single admin-initiated "generate N vouchers" request and its
    approval lifecycle -- see ``constants.VoucherBatchStatus`` for the full
    status write-up and ``docs/voucher/FLOW.md`` for the end-to-end flow.
    """

    __tablename__ = "voucher_batches"

    name: Mapped[str] = mapped_column(String(200), nullable=False)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    location_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("locations.id", ondelete="CASCADE"),
        nullable=True,
    )
    quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    code_length: Mapped[int] = mapped_column(Integer, nullable=False)
    code_prefix: Mapped[str | None] = mapped_column(String(20), nullable=True)
    # How long a voucher grants access *after* first redemption -- distinct
    # from batch_expires_at below. See models.py's module docstring.
    validity_minutes: Mapped[int] = mapped_column(Integer, nullable=False)
    # The batch's own shelf-life: codes not redeemed by this timestamp
    # become permanently invalid, independent of validity_minutes.
    batch_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    max_uses_per_voucher: Mapped[int] = mapped_column(
        Integer, default=1, nullable=False
    )
    # Bandwidth/data cap hint for the future guest/session-management module
    # to enforce -- stored, not enforced, here. See module scope note.
    data_limit_mb: Mapped[int | None] = mapped_column(Integer, nullable=True)
    status: Mapped[str] = mapped_column(
        String(20), default=VoucherBatchStatus.DRAFT.value, nullable=False
    )
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    approved_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    approved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("ix_voucher_batches_organization_id", "organization_id"),
        Index("ix_voucher_batches_location_id", "location_id"),
        Index("ix_voucher_batches_status", "status"),
        Index("ix_voucher_batches_batch_expires_at", "batch_expires_at"),
    )

    def is_batch_expired(self, *, now: datetime) -> bool:
        return self.batch_expires_at is not None and now > self.batch_expires_at

    def __repr__(self) -> str:
        return f"<VoucherBatch(id={self.id}, name={self.name}, status={self.status})>"


class Voucher(BaseModel):
    """A single generated (or imported) voucher code and its redemption
    lifecycle -- see ``constants.VoucherStatus`` and this module's own
    docstring (plaintext code storage, ``expires_at`` timing) for the full
    write-up.

    ``redeemed_identifier`` is a plain string (phone/email/device-MAC, or
    whatever the redeeming guest self-reports), **not** a foreign key: no
    ``Guest`` model exists yet in this codebase (a later module in this same
    BE-010 sequence) -- the identical "self-contained, no FK to a
    not-yet-existing table" posture ``app.domains.otp.models.OtpRequest
    .identifier`` already established. The future ``guest`` module composes
    with this one purely through ``VoucherService.redeem_voucher``'s return
    value, never a shared table or FK.
    """

    __tablename__ = "vouchers"

    batch_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("voucher_batches.id", ondelete="CASCADE"),
        nullable=False,
    )
    code: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    status: Mapped[str] = mapped_column(
        String(20), default=VoucherStatus.UNUSED.value, nullable=False
    )
    use_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    redeemed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_used_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    redeemed_identifier: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # NULL until first redemption -- see module docstring for why this is
    # computed at redeem time, not at generation time.
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("ix_vouchers_batch_id", "batch_id"),
        Index("ix_vouchers_code", "code", unique=True),
        Index("ix_vouchers_status", "status"),
    )

    def is_post_redemption_expired(self, *, now: datetime) -> bool:
        return self.expires_at is not None and now > self.expires_at

    def __repr__(self) -> str:
        return f"<Voucher(id={self.id}, code={self.code}, status={self.status})>"


__all__ = ["VoucherBatch", "Voucher"]
